language: scala

jdk:
  - oraclejdk8

sudo: true

# required to update jdk, there is a compile error with the default version on Travis
addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  - IDEA_SDK=$TRAVIS_BUILD_DIR/SDK/ideaSDK

script:
  # relies on travis supporting sbt-extras launcher
  - sbt -jvm-opts travis/package.jvmopts packagePluginCommunity test:compile
  # run only a typeInference tests because "fast" tests cause travis to timeout
  # - sbt -jvm-opts travis/fastTests.jvmopts runFastTests
  - sbt -jvm-opts travis/fastTests.jvmopts '- $HOME/.m2/repository'


# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $IDEA_SDK

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $IDEA_SDK -name "ideaIC-*.zip" -delete
  # remove all but the newest ideaSDK
  - ls -Art $IDEA_SDK | tail -n 1 | xargs find $IDEA_SDK -maxdepth 1 -mindepth 1 -print -not -name
